### ISSUE TITLE
少侠你的 blog 挂了！

### ISSUE THREAD

**Issue by yxjxx** [Big-Pi/CellSizeCacheDemo#1]
http://bigpi.me/post/ios/ios_huan-cun-cellxing-gao-de-ji-ben-si-lu

**Comment by iShawnWang** [comment]
- 前辈说我的名字不好,所以把邮箱,Github,域名头像,都换了一遍… 
- 现在在 [这里](https://github.com/iShawnWang/BlogDemo/tree/master/CellSizeCacheDemo)
- :)
